name: S3 deploy with CloudFront

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: react build & deploy
    runs-on: ubuntu-latest
    env:
      CI: false

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: React Build
        run: npm run build
        env:
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          REACT_APP_STREAMING_ID: ${{ secrets.REACT_APP_STREAMING_ID }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./build s3://${{ secrets.S3_BUCKET }} --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"
